### ISSUE TITLE
render process can't use node 

### ISSUE THREAD

**Issue by any-u** [nayunhwan/Electron-CRA-TypeScript#2]
today, I use your template. then I found a  problem that render process can't use node. because render process need to use the main process' s node.  the main reason for this problem is that the rendering process runs before the main process. so I wonder if there is a solution

**Comment by nayunhwan** [comment]
Hi, sillyY.
I'm so sorry for the late reply.
Did you solve this problem? or not?

If you don't solve this problem until now, I will check up about this issue.
Thank you for reporting.

**Comment by any-u** [comment]
I read your code again. then i found your main process loads the rendering process at port 3000. I know that in this case, the rendering process can use node. Then I found that your main process configuration is missing webPreferences. nodeIntegration in webPreferences controls whether the rendering process can use node.
